# Copyright 2025 The Tekton Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-pruner-controller-cluster-access
  labels:
    pruner.tekton.dev/release: "devel"
rules:
  # Write permissions to publish events.
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "create"
      - "update"
      - "patch"

  # allows to manage taskruns and pipelineruns
  - apiGroups:
      - "tekton.dev"
    resources:
      - "taskruns"
      - "pipelineruns"
      - "taskruns/finalizers"
      - "pipelineruns/finalizers"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "delete"
      - "patch"
      - "watch"

  # used in webhook
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch

  # used in webhook
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch

  - apiGroups:
      - ""
    resources:
      - namespaces/finalizers
    verbs:
      - update

  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch

  # permissions restricted to specific ConfigMap 
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - tekton-pruner-namespace-spec
    verbs:
      - get
