---
name: Label Checker

permissions: {}

'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check kind labels
    runs-on: ubuntu-latest
    steps:
      - uses: agilepathway/label-checker@57e9f47b4c3c335dda5c903c827d91aa03be807a  # v1.6.101
        with:
          prefix_mode: true
          one_of: "kind/"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
