---
name: Label Checker

permissions: {}

'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:

  check_labels:
    name: Check kind labels
    runs-on: ubuntu-latest
    steps:
      - uses: agilepathway/label-checker@14e5d1a7c2597a1aad5377b2a7726619c9a81f95  # v2.0.1
        with:
          prefix_mode: true
          one_of: "kind/"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
